server:
  port: 8083
  servlet:
    context-path: /lending-service

spring:
  application:
    name: lending-service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8081/eureka/